spring:
  application:
    name: nota-fiscal-lanHouse
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 4
          initial-interval: 5000
          multiplier: 3.0
          max-interval: 15000

server:
  port: 8080

